set_property IOSTANDARD LVCMOS33 [get_ports SPI_SCK]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_MISO]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_SS_0]
set_property PACKAGE_PIN R10 [get_ports SPI_SS_0]
set_property PACKAGE_PIN N7 [get_ports SPI_SCK]
set_property PACKAGE_PIN N8 [get_ports SPI_MOSI]
set_property PACKAGE_PIN R7 [get_ports SPI_MISO]
