set_property IOSTANDARD LVCMOS33 [get_ports SPI_SCK]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_MISO]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_SS_0]
set_property PACKAGE_PIN F12 [get_ports SPI_SS_0]
set_property PACKAGE_PIN F13 [get_ports SPI_SCK]
set_property PACKAGE_PIN E12 [get_ports SPI_MOSI]
set_property PACKAGE_PIN F14 [get_ports SPI_MISO]
